experiment:
  name: oxford_pets_binary_resnet101_like
  seed: 42

data:
  dataset: OxfordIIITPet
  task: binary_classification
  data_dir: ./data
  img_size: 224
  split:
    val_split: 0.2
    stratified: true
  loader:
    batch_size: 32
    num_workers: 1
    pin_memory: true
    shuffle_train: true
    drop_last_train: true
  normalization:
    robust: false
    stats_cache_path: ./data/pet_stats.json
    use_cached_if_available: true
    mean:
      - 0.48293063044548035
      - 0.44492557644844055
      - 0.3957090973854065
    std:
      - 0.2592383325099945
      - 0.25327032804489136
      - 0.2598187029361725
  class_names:
    - cat
    - dog
  num_classes: 2

model:
  blocks_per_stage: [3, 4, 23, 3]
  num_classes: 2
  first_block: conv
  init: kaiming

parameters:
  total: 42504258
  trainable: 42504258

training:
  epochs: 30
  amp: true
  pos_label: 1
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.001
    betas:
      - 0.9
      - 0.999
    weight_decay: 0.0001
  scheduler:
    name: StepLR
    step_size: 30
    gamma: 0.1
  loop:
    train_fn: train_epoch_classification
    val_fn: evaluate_model

results:
  val:
    loss: 0.4084
    roc_auc: 0.9108
    classification_report:
      by_class:
        "0":
          precision: 0.684
          recall: 0.875
          f1: 0.7678
          support: 240
        "1":
          precision: 0.9301
          recall: 0.8044
          f1: 0.8627
          support: 496
      overall:
        accuracy: 0.8274
        macro_avg:
          precision: 0.8071
          recall: 0.8397
          f1: 0.8153
          support: 736
        weighted_avg:
          precision: 0.8498
          recall: 0.8274
          f1: 0.8318
          support: 736

repro_notes:
  - "device was: 'cuda' if available else 'cpu'"
  - Images were resized to 1.14*img_size then center-cropped to img_size before ToTensor
    + Normalize
